name: my_awesome_project 
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: '>=3.2.0 <4.0.0' 
  flutter: '>=3.22.0'


dependencies:
  flutter:
    sdk: flutter

  image: ^4.1.7   # Görüntü işleme için
  camera: ^0.11.2+1 # Kameraya erişim için
  http: ^1.1.0       # Gemini API ile HTTP istekleri için
  path_provider: ^2.1.1 # Geçici dosya yazmak için
  speech_to_text: ^7.3.0 # Konuşmayı metne çevirme için
  flutter_tts: ^4.2.3   # Metni sese dönüştürme için
  permission_handler: ^12.0.1
  flutter_bluetooth_serial: ^0.4.0
  firebase_core: ^4.3.0 # Firebase core için
  cloud_firestore: ^6.1.1 # Firestore için
  google_mlkit_object_detection: ^0.15.0 # Nesne tespiti için
  google_mlkit_face_detection: ^0.13.1 # Yüz tespiti için
  firebase_vertexai: ^2.2.0 # Firebase Vertex AI için
  googleapis_auth: ^2.0.0
  googleapis: ^15.0.0
  firebase_storage: ^13.0.5 # Firebase Storage için
  tflite_flutter: ^0.12.1  # TFLite motoru
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true 
  assets:
    - assets/labels.txt
    - assets/models/ssd_mobilenet.tflite
    - assets/service_account.json
    - assets/mobilefacenet.tflite

 
